version: '2.33.1'

services:
  # mariadb:
  #   build: ./requirements/mariadb
  #   env_file: ../.env
  #   volumes:
  #     - mariadb_data:/var/lib/mysql
  #   networks:
  #     - inception

  # wordpress:
  #   build: ./requirements/wordpress
  #   env_file: ../.env
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   networks:
  #     - inception

  nginx:
    build: ./requirements/nginx
    ports:
      - "80:80"
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
