# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fcoullou <fcoullou@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/24 14:39:12 by fcoullou          #+#    #+#              #
#    Updated: 2025/04/24 14:39:13 by fcoullou         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM mariadb:10.5
ENV MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MARIADB_DATABASE}
ENV MYSQL_USER=${MARIADB_USER}
ENV MYSQL_PASSWORD=${MARIADB_PASSWORD}
EXPOSE 3306
